# image: drone_area.pgm
image: /home/ub/Downloads/ard/ardu_ws/src/map_server/config/drone_area.pgm
mode: trinary
resolution: 0.05
origin: [-10.4, -4.35, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25